server.port: 9001
spring:
  session.store-type: jdbc
  jpa:
    show-sql: true
#  datasource:
#    url: jdbc:postgresql://localhost:5433/auth
#    driver-class-name: org.postgresql.Driver
#    username: user
#    password: password
#    hikari.schema: public

clients:

  auth-code-pkce-client:
    clientId: demo-auth-code-pkce-client
    secret: 123456
    authenticationMethods:
      - client_secret_post
    grants:
      - authorization_code
      - refresh_token
    redirectUris:
      - https://oidcdebugger.com/debug
    scopes:
      - openid
    client-settings:
      pkce: true
      consent: false

  auth-code-client:
    clientId: demo-auth-code-client
    secret: 123456
    authenticationMethods:
      - client_secret_post
    grants:
      - authorization_code
      - refresh_token
    redirectUris:
      - https://oidcdebugger.com/debug
    scopes:
      - openid

  client-credentials-client:
    clientId: demo-client-credentials-client
    secret: 123456
    authenticationMethods:
      - client_secret_post
    grants:
      - client_credentials
